### ISSUE TITLE
recursion not working?

### ISSUE THREAD

**Issue by bricerebsamen** [ros-infrastructure/rosdep#289]
I have a package A that depends on a package B that depends on a package ... etc ... that depends on velodyne_pointcloud, where A, B, C ... are my own packages.

One would expect 'rosdep install A' to install velodyne_pointcloud

first of all 'rosdep install A' fails because it cannot find B
so I use the -i flag
but it does not recurse

**Comment by dustingooding** [comment]
I'd like to bring this up again, because I'm running into the same situation that @bricerebsamen came across.  The solution presented solves a different problem (that is, installing all the dependencies of all the packages in an entire workspace) which is a superset of the specific problem presented.

Say we have packages A, B, C, and D in a workspace.  A depends on B, B depends on C, C depends on a system package, and D is mostly stand-alone.  If I say `rosdep install -i A`, C's system dependency will not be installed, and therefore A will not function correctly.  Yes, I could `rosdep install` the whole workspace, but now D's dependencies are installed, and I don't need them to run A.

You might say, "Well, just don't include what you don't need.  Trim back your workspace."

Take a different example.  Say I have a repository that has multiple packages in it, some more library in nature suitable for running on-robot, and some more UI in nature suitable for running off-robot.  It may make sense to keep the packages in the same repo, because they share code and it helps to keep development consistent.  Let's say I include that repo in my on-robot workspace and another one of my packages depends on it.  So, package A depends on repo/not-UI package, and repo/not-UI depends on a system package.  But the workspace still has repo/UI package in it, and it depends on UI-related system dependencies.  If I am forced to `rosdep install` the whole workspace as the only way to "recursively rosdep install", now my robot has unnecessary UI system dependencies installed.

Yes, I could split up my packages into their own repos, but that can get very painful, very fast.

So, what if `rosdep install` just worked recursively?

**Comment by wjwwood** [comment]
@dustingooding I don't think it's a bad idea to have an option that does this, but I'd shy away from making it the default since you'd have to know that the change in behavior doesn't break any existing scripts.

Unfortunately though, I don't think any of the rosdep maintainers will have time to implement it. I'd suggest working with anyone else that's interested in this feature and put together a pull request that adds an option to install that will consider recursive dependencies.
