### ISSUE TITLE
Option to skip installing test dependencies of packages

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/rosdep#317]
Since for format 2 of the package.xml spec test dependencies must be considered it would be nice to optionally disable test dependencies.

**Comment by kmhallen** [comment]
It would be nice to optionally disable build and run dependencies as well.

**Comment by emersonknapp** [comment]
This feature would be useful as a general ability to enable/disable any class of package.xml dependencies. For example, you could run it against a ros2 `install` directory with only `run_depend` enabled, in order to get runtime dependencies on a system where you specifically don't want to install build tools.

**Comment by m2-farzan** [comment]
I think we can close this. The feature has been implemented in this PR: https://github.com/ros-infrastructure/rosdep/pull/789

**Comment by nuclearsandwich** [comment]
> I think we can close this. The feature has been implemented in this PR: #789

Agreed.
