### ISSUE TITLE
rosdep still tries to `brew tap ros/indigo` on OS X

### ISSUE THREAD

**Issue by furushchev** [ros-infrastructure/rosdep#383]
I wanted to install dependent packages on my catkin workspace, and used `rosdep` as I do on Linux:

```
$ cd /path/to/catkin_workspace
$ rosdep install -r --from-paths src --ignore-src
Error: No available formula for hokuyo_node
Please tap it and then try again: brew tap ros/indigo
...
```

I think tap `ros/indigo` is not available because there is no repository named `homebrew-indigo` on https://github.com/ros`.

Any idea?

**Comment by wjwwood** [comment]
That package, `hokuyo_node`, is neither installed on your computer nor in your workspace, but one of your packages depends on it. Therefore `rosdep` will naively try to install it. This works on Ubuntu because we make binary packages for all released packages including `hokuyo_node`, but this is not the case for Homebrew. So, to solve this issue you'll need to add `hokuyo_node` to your workspace and try again, resolving any missing ROS package dependencies in this way recursively. You can use `rosinstall_generator` to make sure you get all the ROS packages you need for a particular package in your workspace.
