### ISSUE TITLE
install only the top-level dependencies of a package?

### ISSUE THREAD

**Issue by samlelouch** [ros-infrastructure/rosdep#500]
I am working on Ubuntu 16.04 ARM and looking to install ROS packages. However, besides rosdep, is there an `apt-get install` command or any other command that will let me install only the package's top-level dependencies and not all of them recursively?

**Comment by wjwwood** [comment]
Besides `rosdep`? No, not that I'm aware of. `rosinstall_generator` is able to control the "depth" of the dependencies, but it just clones source code. It doesn't install things from the package manager.

**Comment by wjwwood** [comment]
Also, you might get better or faster feedback on answers.ros.org, but you'll probably want to include more information about what you're trying to accomplish. Since this isn't a bug or feature request of `rosdep` (yet), I'm going to close this in favor of asking on answers.ros.org, see also: http://wiki.ros.org/Support
